# 配置服务器端口
server:
  port: 8080

spring:
  application:
    # 应用名称 (可选)
    name: reggie_take_out
  # 配置Druid数据库连接池
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: xsh981104
  # 配置Redis连接
  redis:
    host: 192.168.148.100
    port: 6379
    password: xsh981104
    database: 0
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0
        # 等待时长
        max-wait: 100ms

# 配置Mybatis-Plus
mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    # 例如：属性名映射 user_name --> userName
    # 例如：类名映射 address_book --> AddressBook
    map-underscore-to-camel-case: true
    # 开启MP运行日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

# 文件保存路径
reggie:
  path: G:\img\